### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dev1980**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Great job @dev1980 👏
Nice work on this project. But before merging to master we need to do some changes in order to match Microverse guidelines.

- [ ] The search field from the navbar should be an `input` HTML tag with the *focus* effect enabled

- [ ] Microverse guidelines require a different approach from the original page for loading image. You must load all images in a div tag, using the background. This applies to the 3 main sentences and all 4 promo images.

- [ ] Your hero image it's not loading. Looks like the image file has a different name from one that you are using to load the background

- [ ] Use div tag instead img tag to load the image for the 3 main sentences. In the original page, these 3 main sentences are actually images. No need to use img tag.

- [ ] Microverse guidelines require that the footer must starts 'section class="gallary-1"'. Move this section to the footer tag.

- [ ] Change your header tag to a main tag.

- [ ] Its best practice to include in your readme file the links from the original project and the assignment.

kindly make these changes and submit for code review again.

**Comment by mosaaleb** [comment]
Reviewing

**Review by mosaaleb — APPROVED** [review]
### Congratulations @dev1980 :clap:

#### You can merge into master :+1:

Good luck with the next projects.

Happy coding :computer:

**Comment by dev1980** [comment]
Approved for merge

**Pull request merged**
